### ISSUE TITLE
Some custom payloads and white_notification_icon.png are not compatable :(

### ISSUE THREAD

**Issue by hopesourav** [pushbots/phonegap#42]
I am using few custom payloads such as -
"InboxStyleOff" => "true"
"BigTextStyle"=> "true"
"bigText"=> "XYZ....."

However, my notification icon (white_notification_icon.png in res/drawable) turns white box again when the above payloads are used!
It works normal with "largeIcon" & "customNotificationTitle" .

Please check and let me know!

**Comment by joanebrown** [comment]
+1

**Comment by joanebrown** [comment]
Why you closed this issue?

**Comment by hopesourav** [comment]
@joanebrown this is not closed. #41  is closed.

**Comment by joanebrown** [comment]
Yes, I had a mistake hehe

**Comment by hopesourav** [comment]
Let @AbdullahDiaa  reply

**Comment by AbdullahDiaa** [comment]
This has been fixed with latest Android library.

First generate small Icon:
https://romannurik.github.io/AndroidAssetStudio/icons-notification.html#source.space.trim=1&source.space.pad=0&name=ic_stat_pushbots_sicon

Then copy it to _platforms/android/res_ folder, must be titled _ic_stat_pushbots_sicon_

And for phonegap build, check out this link for more details:
https://github.com/phonegap/build/issues/472#issuecomment-172662620

**Comment by hopesourav** [comment]
Hi ...
When Can we expect 1.4.x to be available via npn ?

**Comment by amrsobhy** [comment]
@hopesourav you can do the following until it's available on npm 

`cordova plugin install https://github.com/pushbots/phonegap/`

**Comment by AbdullahDiaa** [comment]
@hopesourav The plugin has been updated on npm to 1.4.0 with latest SDKs.

**Comment by hopesourav** [comment]
Hi @AbdullahDiaa and @amrsobhy ,

Guys Thanks! Got the 1.4.0 update via npm.
However, the issue still exists. Maybe I have made some mistake . Could you pls verify the steps -
1. Updated 1.4.x version of Pushbot and Android libraries via SDK manager.
2. Copied the downloaded icons to platforms/android/res folder, and  titled them ic_stat_pushbots_sicon.png instead of white_notification_icon.png 
3. rebuild the app using CLI

Still the white icon appears with the below payloads as reported earlier -
"InboxStyleOff" => "true"
"BigTextStyle"=> "true"
"bigText"=> "XYZ....."

Request you to pls guide me. 

Regards,
Sourav

**Comment by amrsobhy** [comment]
@hopesourav Connect your device to a computer running Android studio and check and share logcat under PB3 tag.

**Comment by hopesourav** [comment]
Hi @AbdullahDiaa and @amrsobhy ,

[logcat PB2 log.txt](https://github.com/pushbots/phonegap/files/572192/logcat.PB2.log.txt)

Pls let me know if u guys need anything else!

Regards,
Sourav

**Comment by hopesourav** [comment]
1 more thing :

Could you pls guide me how to update the pushbot library to 3.0.1 ?

It seems I am using the library pushbots-lib-2.0.13. And updating the plugin to 1.4.0 has not automatically updated my library.

I will be really great if we can schedule a call sometime.

Regards,
Sourav

**Comment by AbdullahDiaa** [comment]
@hopesourav It seems you're still using old plugin, if you updated to 1.4.x+ you'll automatically on Pushbots library v3
