### ISSUE TITLE
Notification:clicked/received not being called

### ISSUE THREAD

**Issue by Kyvyas** [pushbots/phonegap#49]
Hi, we're trying to enable deep linking in our app so that users can click on a notification which takes them to a specific screen. Currently, we see logging for initialisation - "Initialise Success" and registration, however we do not seem to receive any response from notification clicked/received. Here is our code:

```
.service('PushNotificationsService', function( ) {
  var init = function() {
    if (ionic.Platform.isWebView()) {
      Pushbots = PushbotsPlugin.initialize(Constants.pushbotsAppId, {"android": {"sender_id": "xxxxx"}});
      Pushbots.on("notification:clicked", function(data){
          console.log("clicked:" + JSON.stringify(data));
        });
      Pushbots.on("notification:received", function(data){
        console.log("received:" + JSON.stringify(data));
      });
      Pushbots.on("registered", function(data){
        console.log("registration id:" + data);
      });
      console.log("Initialise success")
    }
  };
```

PushNotificationsService.init() is called when the app opens within our $ionicPlatform.ready function.

Do you have any advice on where to deal with notification interaction?

Thanks!

**Comment by amrsobhy** [comment]
@Kyvyas  You are using a deprecated syntax. Please, use the latest SDK and syntax.

**Comment by Kyvyas** [comment]
Thanks for your reply. We're working with the ionic framework

We tried `PushbotsPlugin.on` syntax and it also did not work - any help appreciated

**Comment by amrsobhy** [comment]
Are you using the syntax below with the latest SDK?

```
// Should be called once the notification is clicked
window.plugins.PushbotsPlugin.on("notification:clicked", function(data){
    console.log("clicked:" + JSON.stringify(data));
});

```

If yes, then please provide more info/log to reproduce the problem. Also what's your platform and OS version?

**Comment by Kyvyas** [comment]
We've tried that, as detailed in the documentation but received the following error:

```
Cannot read property 'on' of undefined
```

We are using Ionic and building onto a Nexus 5x on Android 7

**Comment by amrsobhy** [comment]
Are you able to try on a different testing device with Android 5? Need to know if it's Android 7 related bug or an implementation issue.

**Comment by AbdullahDiaa** [comment]
You should include latest SDK to be able to use on listener.
The problem should be fixed in latest release.

**Comment by Kyvyas** [comment]
Thanks for your response. The code you've updated looks like it for ios, not android, however so hasn't made any difference to our issue. Also - looking like the change hasn't been released yet, it's still on 1.3.9.
https://www.npmjs.com/package/pushbots-cordova-plugin

I'm still not able to get any response to a clicked notification. I'm using the updated SDK(1.4. and am not receiving any errors, pushbots is being initialised. I have added logging to the notification:clicked event but it never fires.

Thanks again,

Katya

**Comment by AbdullahDiaa** [comment]
@Kyvyas The plugin has been updated on npm to 1.4.0 with latest SDKs.
Can you please try the latest version from npm and let me know if the problem persists?
